CREATE TABLE events (
eid INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
edate date NOT NULL,
time timestamp NOT NULL,
title VARCHAR (200) NOT NULL,
duration VARCHAR (20) NOT NULL,
price INT NOT NULL,
elimit INT NOT NULL,
location VARCHAR (200) NOT NULL,
image VARCHAR (200) NOT NULL,
description VARCHAR (500) NOT NULL
);
