from wtforms import Form, DateTimeField, StringField, SubmitField, HiddenField, RadioField, BooleanField, TextAreaField, FileField, SelectField, validators
from wtforms.validators import InputRequired, DataRequired, ValidationError, url

class RegistrationForm(Form):
    rid = HiddenField("rid", description="rid")
    order_id = HiddenField("Order ID", description="Order ID")
    camper1_name = StringField("Participant Name", [validators.required()], description="Participant Name")
    camper1_age = StringField("Participant Age", [validators.required()], description="Participant Age")
    camper2_name = StringField("Participant 2 Name", description="Participant 2 Name")
    camper2_age = StringField("Participant 2 Age", description="Participant 2 Age")
    camper3_name = StringField("Participant 3 Name", description="Participant 3 Name")
    camper3_age = StringField("Participant 3 Age", description="Participant 3 Age")
    parent_name = StringField("Name", [validators.required()], description="Name")
    parent_address = StringField("Address", [validators.required()], description="Address")
    parent_city = StringField("City", [validators.required()], description="City")
    parent_state = StringField("State", [validators.required()], description="State")
    parent_zip = StringField("Zip Code", [validators.required()], description="Zip Code")
    parent_email = StringField("Email", [validators.required()], description="Email")
    parent_phone = StringField("Phone", [validators.required()], description="Phone")
    parent_em_name = StringField("Emergency Contact Person", description="Emergency Contact Person")
    parent_em_phone = StringField("Emergency Phone", description="Emergency Phone")
    pickup1_name = StringField("Name", description="Name")
    pickup1_phone = StringField("Phone", description="Phone")
    pickup2_name = StringField("Name 2", description="Name 2")
    pickup2_phone = StringField("Phone 2", description="Phone 2")
    session_detail = HiddenField("Session Detail", description="Session Detail")
    treatment_permission = BooleanField("Emergency Treatment Permission", [validators.required()], description="")
    photo_release = BooleanField("Photo/Social Media Release", [validators.required()], description="")
    signature = StringField("Signature", [validators.required()], description="")
    submit = SubmitField("Continue", description="Continue")


class RegFormWheelWars(Form):
    rid = HiddenField("rid", description="")
    status = HiddenField("status", description="")
    registration_name = HiddenField("Registration Name", description="")
    event_date = HiddenField("Event Date", description="")
    name = StringField("Name", description="Name")
    phone_number = StringField("Phone Number", description="Phone Number")
    email = StringField("Email", description="Email")
    age = StringField("Age", description="Must be 18 years or older")
    shirt_size = StringField("T-Shirt Size", description="T-Shirt Size")
    city = StringField("City", description="City")
    career = StringField("Career", description="Career")
    use_wheel = SelectField("Can you use a pottery wheel?", choices=[('Yes', 'Yes'), ('No', 'No'), ('Need practice', 'Need practice')])
    experience = SelectField("Pottery Experience", choices=[('None', 'None'), ('Taken lessons', 'Taken lessons'), ('Own a wheel', 'Own a wheel')])
    items = StringField("Pottery Items", description="List pottery items you can make")
    interests = StringField("Pottery Interests", description="Pottery Interests")
    photos = HiddenField("Photos", description="")
    photo_release = BooleanField("Photo/Social Media Release", [validators.required()], description="")
    signature = StringField("Signature", [validators.required()], description="")
    submit = SubmitField("Continue", description="Continue")


class RegFormPaintWars(Form):
    rid = HiddenField("rid", description="")
    status = HiddenField("status", description="")
    registration_name = HiddenField("Registration Name", description="")
    event_date = HiddenField("Event Date", description="")
    name = StringField("Name", description="Name")
    phone_number = StringField("Phone Number", description="Phone Number")
    email = StringField("Email", description="Email")
    age = StringField("Age", description="Must be 18 years or older")
    instagram = StringField("Instagram - so we can promote your art", description="Instagram")
    can_paint = SelectField("Can you paint 18 x 24 inch canvas in 20 minutes?", choices=[('Yes', 'Yes'), ('No', 'No'), ('Maybe', 'Maybe')])
    can_promote = SelectField("Are you willing to help promote the event?", choices=[('Yes', 'Yes'), ('No', 'No'), ('Maybe', 'Maybe')])
    photo_release = BooleanField("Photo/Social Media Release", [validators.required()], description="")
    signature = StringField("Signature", [validators.required()], description="")
    submit = SubmitField("Continue", description="Continue")

